export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_ERROR';
export const FETCH_LOCATIONS_ERROR = 'FETCH_LOCATIONS_ERROR';

export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const FETCH_QUERY_POST_SUCCESS = 'FETCH_QUERY_POST_SUCCESS';
export const FETCH_QUERY_POST_ERROR = 'FETCH_QUERY_POST_ERROR';

export const FETCH_QUERY_CATG_SUCCESS = 'FETCH_QUERY_CATG_SUCCESS';
export const FETCH_QUERY_CATG_ERROR = 'FETCH_QUERY_CATG_ERROR';

export const FETCH_QUERY_LOC_SUCCESS = 'FETCH_QUERY_LOC_SUCCESS';
export const FETCH_QUERY_LOC_ERROR = 'FETCH_QUERY_LOC_ERROR';

export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_ERROR = 'FETCH_CATEGORY_ERROR';

export const FETCH_MAIN_CATEGORY_SUCCESS = 'FETCH_MAIN_CATEGORY_SUCCESS';
export const FETCH_MAIN_CATEGORY_ERROR = 'FETCH_MAIN_CATEGORY_ERROR';

export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS';
export const FETCH_LOCATION_ERROR = 'FETCH_LOCATION_ERROR';

export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';
export const FETCH_SINGLE_ERROR = 'FETCH_SINGLE_ERROR';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR';

export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_ERROR = 'FETCH_COMMENT_ERROR';
