export const Routes = {
    agric: '/page/Agric',
    artCraft: '/page/Art-Craft',
    baleImports: '/page/Bale-Imports',
    electronics: '/page/Electronics',
    fashion: '/page/Fashion',
    food: '/page/Food',
    home: '/',
    admin: '/page/Admin',
    interiorDecor: '/page/Interior-Decor',
    prints: '/page/Prints',
    properties: '/page/Properties',
    services: '/page/Services',
    vehicles: '/page/Vehicles',
    categories: '/Categories',
    locations: '/Locations',
    pageParam: '/page/:page/:id',
    page: '/page/',
    locationParam: '/location/:location',
    location: '/location/',
    pages: '/page/:name',
    about: '/About',
    contact: '/Contact',
    advertise: '/Advertise',
    promote: '/Promote',
    privacy: '/Privacy',
    terms: '/Terms',
    write: '/Write-us',
};

